---
title: "binning"
author: "chang han"
date: "4/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
suppressPackageStartupMessages({
  library(dplyr)
})
```

```{r}
chromosome_name<-c("chr1","chr2","chr3","chr4","chr5","chr6","chr7","chr8","chr9","chr10","chr11","chr12","chr13","chr14","chr15","chr16","chr17","chr18","chr19","chr20","chr21","chr22","chrX","chrY")
chromosome_length<-c(249250612,243199373,198022430,191154276,180915260,171115067,159138663,146364022,
                     141213431,135534747,135006516,133851895,115169878,107349540,102531392,90354753,
                     81195210,78077248,59128983,63025520,48129895,51304566,155270560,59373566)
human_chromosome<-data.frame(chromosome_name,chromosome_length)
head(human_chromosome)
exercise_paired<-read.csv(file="exercise_paired.csv")

exercise_second_order<-read.csv(file="exercise_second_order.csv")
fasting_rest<-read.csv(file="fasting_rest.csv")
cdp_compmultsign<-read.csv(file="CDP_CompMultSign_list.csv")

```



```{r}
find_bins<-function(chr,start,end,bin_size=200000){
  if(is.na(chr)| is.na(start)|is.na(end)){
    return(NA)
  }
  else{
  #t<-paste0("chr",as.character(chr))
  #chr_length<-human_chromosome[chromosome_name==t,]$chromosome_length
  start_bin<-floor(start/bin_size)+1
  end_bin<-floor(end/bin_size)+1
  total_bin<-paste0(seq(start_bin,end_bin),collapse="&")
  return(total_bin)
  }
  
}
```
```{r}
bin1<-mapply(find_bins, exercise_paired$chr, exercise_paired$start_pos, exercise_paired$end_pos)
bin2<-mapply(find_bins, exercise_second_order$chr, exercise_second_order$start_pos, exercise_second_order$end_pos)
bin3<-mapply(find_bins, fasting_rest$chr, fasting_rest$start_pos, fasting_rest$end_pos)
bin4<-mapply(find_bins, cdp_compmultsign$chr, cdp_compmultsign$pos, cdp_compmultsign$pos)
df1<-cbind(exercise_paired,bin=bin1)[,1:11]
df2<-cbind(exercise_second_order,bin=bin2)[,1:11]
df3<-cbind(fasting_rest,bin=bin3)[,1:11]
df4<-cbind(cdp_compmultsign,bin=bin4)

```
```{r}
write.csv(df1,"exercise_paired_bin.csv", row.names = FALSE)
write.csv(df2,"exercise_second_order_bin.csv", row.names = FALSE)
write.csv(df3,"fasting_rest_bin.csv", row.names = FALSE)
write.csv(df4,"cdp_MultSign_bin.csv", row.names = FALSE)
```

```{r}
library("chromPlot")
```
```{r}
chromplot_df1<-dplyr::select(df1, chr, start_pos, end_pos)
chromplot_df1<-na.omit(chromplot_df1)
chromplot_df1$chr<-as.character(chromplot_df1$chr)
colnames(chromplot_df1)<-c("Chrom","Start","End")
chromplot_df2<-dplyr::select(df2, chr, start_pos, end_pos)
chromplot_df2<-na.omit(chromplot_df2)
chromplot_df2$chr<-as.character(chromplot_df2$chr)
colnames(chromplot_df2)<-c("Chrom","Start","End")
chromplot_df3<-dplyr::select(df3, chr, start_pos, end_pos)
chromplot_df3<-na.omit(chromplot_df3)
chromplot_df3$chr<-as.character(chromplot_df3$chr)
colnames(chromplot_df3)<-c("Chrom","Start","End")

```
```{r}

```


```{r}
data(hg_gap)
data(hg_cytoBandIdeo)
#gaps specifies the coordinates that we use to plot on the chromosome, hg_gap is provided in package
#below is the plot of genes in exercise_pair, bin_size=200kb,black circile is centromere
chromPlot(gaps=hg_gap,annot1=chromplot_df1,bin=200000)
chromPlot(gaps=hg_gap,annot1=chromplot_df2,bin=200000)
chromPlot(gaps=hg_gap,annot1=chromplot_df3,bin=200000)
```





